version = "1.1.15"

[class]
"dev.zed.Zed" = "ó°¬¡"
firewall = "ó±¨‘"
Code = "ó°¨"
blueman = "ïŠ“"
DEFAULT = "ï™"
"vscodium.codium" = "ï²"
jetbrains = "î ˆ"
rustdesk = "îˆ†"
flameshot = "ó°¹‘"
"org.mozilla.firefox" = "ó°ˆ¹"
waybar = "ï¢"
zen = "ó°º•"
telegram = "ï‹†"
kitty = "ï„ "
Junction = "ó°‡"
mpv = "ï®"
pcsx2 = "ó°”"
imv = "ï€¾"
nm-applet = "ó°›µ"
"org.pulseaudio.pavucontrol" = "ï€¨"
nm-connection-editor = "ó°¤€"

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]

[title_in_class.".*"]
"(?i)Unlock Keyring" = "ï‚„"

[title_in_class.".*zen.*"]
"Spring" = "îš”"
"freeCodeCamp" = "î‰‚"
"LinkedIn" = "ï‚Œ"
"Rust" = "î¨"
"YouTube" = "ó°—ƒ"
"Codeforces" = "ó±•"
"Codeberg" = "ïŒ°"
"Debian" = "ó°£š"
"Ubuntu" = "î½²"
"HackerRank" = "îº¥"
"Search" = "îš"
"GitHub" = "ï‚›"
"Bitwarden" = "ó°€"
"Discord" = "ï‡¿"
"Stack Exchange" = "ï†"
"CodePen" = "îœ–"
"AWS" = "ïƒ¯"
"Python" = "îœ¼"
"GNU" = "î¹"
"Mastodon" = "ó°«‘"
"Hyprland" = "ï™"
"Wikipedia" = "ï‰¦"
"GitLab" = "ïŠ–"
"Reddit" = "ïŠ"
"Font Awesome" = "ó°€º"
"Drive" = "ï‹Ÿ"
"Product Hunt" = "ïŠˆ"
"WhatsApp" = "ó°–£"
"Azure" = "î¯˜"
"DEV" = "î»´"
"Figma" = "î½‡"
"Fedora" = "î½†"
"React" = "îº"
"Teams" = "ó°Š»"
"Stack Overflow" = "ï…¬"
"Hacker News" = "ïˆ»"
"Steam" = "ó°““"
"Java" = "îœ¸"
"NeetCode" = "ó±¯"
"npm" = "îœ"
"Arch" = "ó°£‡"
"Telegram" = "ï‹†"
"Flathub" = "ïŒ¤"
"Medium" = "ïˆº"

[title_in_class.".*kitty.*"]
"(?i)Yazi" = "ï„•"
"(?i)btop" = "ğŸ…±"
"(?i)micro" = "Î¼"

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"" = "^$"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}{delim}"
client_fullscreen = "[{icon}]{delim}"
client_active = "<b>{icon}</b>"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
